name: PUSH-IMAGE-FROM-DOCKERHUB-TO-AWS

on:
  workflow_run:
    workflows: ["PUSH-IMAGE-TO-DOCKERHUB"]
    types:
      - completed

jobs:
  buid:
    runs-on: self-hosted

    steps:
      - name: Pull DOCKER IMAGE from DOCKER HUB
        run: sudo docker pull devcloudarmel/handleform:1.0

      - name: Delete old container
        run: sudo docker rm -f handleform-container || true
      
      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name handleform-container devcloudarmel/handleform:1.0