name: PUSH-IMAGE-FROM-DOCKERHUB-TO-AWS

on:
  workflow_run:
    workflows: ["PUSH-IMAGE-TO-DOCKERHUB"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull DOCKER IMAGE from DOCKER HUB
        run: sudo docker pull devcloudarmel/handleform:1.0

      - name: Stop and remove old container if exists
        run: |
          if [ "$(docker ps -q -f name=handleform-container)" ]; then
            sudo docker stop handleform-container
            sudo docker rm handleform-container
          fi

      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name handleform-container devcloudarmel/handleform:1.0

      - name: Remove dangling images
        run: sudo docker image prune -f
