name: PUSH-IMAGE-TO-DOCKERHUB

on:
  pull_request:
    types: 
        closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Login to docker hub
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build docker image devcloudarmel/image_name:tag
        run: docker build -t devcloudarmel/handleform:1.0 .
      
      - name: Push image to docker hub
        run: docker push devcloudarmel/handleform:1.0
